version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - proxy
    environment:
      - CAM_PROXY_CONFIG=${CAM_PROXY_CONFIG}
    volumes:
      - ./app:/app
      - ./snapshots:/app/snapshots
  
  proxy:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-proxy
    restart: unless-stopped
    ports:
      - "8554:8554/tcp"
      - "8554:8554/udp"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pettracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: