version: "3.9"

services:
  server:
    build: 
      context: .
      target: server-dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - proxy
    environment:
      - CAM_PROXY_CONFIG=${CAM_PROXY_CONFIG}
      - ROBOFLOW_API_URL=${ROBOFLOW_API_URL}
      - ROBOFLOW_API_KEY=${ROBOFLOW_API_KEY}
      - ROBOFLOW_MODEL_ID=${ROBOFLOW_MODEL_ID}

    volumes:
      - ./server/app:/app
      - ./server/snapshots:/app/snapshots
  
  proxy:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-proxy
    restart: unless-stopped
    ports:
      - "8554:8554/tcp"
      - "8554:8554/udp"
    volumes:
      - ./server/mediamtx.yml:/mediamtx.yml:ro

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pettracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: